// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXh7PIvAkyde92SX8MXjDNotBy3pS573M',
    appId: '1:1015259126768:web:813fb24c025aaf0aac1b35',
    messagingSenderId: '1015259126768',
    projectId: 'blog-app-help',
    authDomain: 'blog-app-help.firebaseapp.com',
    storageBucket: 'blog-app-help.firebasestorage.app',
    measurementId: 'G-B6C8XZ3MZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DUo6yHTGflEscew_9E-2fksgfstnUwQ',
    appId: '1:1015259126768:android:1d2de1e7f22fff48ac1b35',
    messagingSenderId: '1015259126768',
    projectId: 'blog-app-help',
    storageBucket: 'blog-app-help.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxu4kKlH4-s16DY4d9z11BIgwbWrvx0M',
    appId: '1:1015259126768:ios:2e47f9b709140f0cac1b35',
    messagingSenderId: '1015259126768',
    projectId: 'blog-app-help',
    storageBucket: 'blog-app-help.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxu4kKlH4-s16DY4d9z11BIgwbWrvx0M',
    appId: '1:1015259126768:ios:2e47f9b709140f0cac1b35',
    messagingSenderId: '1015259126768',
    projectId: 'blog-app-help',
    storageBucket: 'blog-app-help.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXh7PIvAkyde92SX8MXjDNotBy3pS573M',
    appId: '1:1015259126768:web:3a1d1b4e5983cf4bac1b35',
    messagingSenderId: '1015259126768',
    projectId: 'blog-app-help',
    authDomain: 'blog-app-help.firebaseapp.com',
    storageBucket: 'blog-app-help.firebasestorage.app',
    measurementId: 'G-NXZR1NLTKR',
  );
}
